steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'demo'
    args: ['build', '-t', 'gcr.io/zurgraphic-467503/spring-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/zurgraphic-467503/spring-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - spring-app
      - --image=gcr.io/$PROJECT_ID/spring-app
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
